.PHONY: dev fmt lint test coverage build integration \
        lock-dependencies lock-docs-dependencies lock-app-dependencies lock-mcp-dependencies \
        docs docs-install docs-build docs-serve docs-clean \
        app-install app-build app-lint app-test \
        mcp-install mcp-build mcp-lint mcp-test clean

UV_RUN := uv run --exact --all-extras
UV_TEST := $(UV_RUN) pytest -n 10 --timeout 60 --durations 20

# After ``uv lock`` resolves through the internal PyPI proxy, the lock is tainted with
# proxy URLs. This rewrites the registry index and every per-package download URL back to
# the public PyPI hosts, and drops the proxy-only ``size`` field, so the committed lock is
# identical for contributors inside Databricks (proxy) and outside (public PyPI).
SANITIZE_LOCK := perl -pi -e 's|registry = "https://[^"]*"|registry = "https://pypi.org/simple"|g; s|url = "https://[^/"]+/packages/|url = "https://files.pythonhosted.org/packages/|g; s|, size = \d+||g'

# npm lockfiles are likewise tainted with the internal npm proxy host after ``npm install``
# runs through it. Swap the proxy host back to the public npm registry; the paths and the
# integrity hashes are identical, so the committed lock installs cleanly on public runners.
SANITIZE_NPM_LOCK := perl -pi -e 's|https://npm-proxy\.cloud\.databricks\.com/|https://registry.npmjs.org/|g'

# Library:
dev:
	uv sync --all-extras

fmt:
	uv run ruff format src tests
	uv run ruff check --fix src tests
	uv run mypy src

lint:
	uv run ruff format --check src tests
	uv run ruff check src tests
	uv run mypy src

test:
	uv run pytest tests/unit

coverage:
	uv run pytest tests/unit --cov=policy_agent --cov-report=term-missing --cov-report=xml

build:
	uv build --wheel

integration:
	uv run pytest tests/integration -m integration

# Regenerate the library lock and sanitize proxy URLs out of it.
lock-dependencies:
	uv lock
	$(SANITIZE_LOCK) uv.lock

# Regenerate the docs bun lock and sanitize the proxy host out of it.
lock-docs-dependencies:
	cd docs && bun install
	$(SANITIZE_NPM_LOCK) docs/bun.lock

# Documentation (fumadocs, built with bun; the API reference is generated by pydoc-markdown):
docs-install:
	cd docs && bun install --frozen-lockfile

docs-build: docs-install
	cd docs && uv run --project .. pydoc-markdown && bun run build && rm -rf site && mv out site

docs: docs-build

docs-serve: docs-build
	cd docs && bun run dev

docs-clean:
	rm -rf docs/.next docs/.source docs/out docs/site docs/node_modules docs/content/docs/api/sidebar.json

# App:
app-install:
	cd app && uv sync --group dev
	cd app/src/policy_agent_app/ui && npm ci

# Regenerate the app locks (Python + UI npm) and sanitize proxy URLs out of both.
lock-app-dependencies:
	cd app && uv lock
	$(SANITIZE_LOCK) app/uv.lock
	cd app/src/policy_agent_app/ui && npm install
	$(SANITIZE_NPM_LOCK) app/src/policy_agent_app/ui/package-lock.json

app-build:
	cd app && uv run python scripts/build_app.py

app-lint:
	cd app && uv run ruff format --check src tests
	cd app && uv run ruff check src tests
	cd app && uv run mypy src

app-test:
	cd app && uv run pytest tests

# MCP server (custom MCP server deployed as a Databricks App):
mcp-install:
	cd mcp && uv sync --group dev

# Regenerate the MCP app lock and sanitize proxy URLs out of it.
lock-mcp-dependencies:
	cd mcp && uv lock
	$(SANITIZE_LOCK) mcp/uv.lock

mcp-build:
	cd mcp && uv run python scripts/build_app.py

mcp-lint:
	cd mcp && uv run ruff format --check src tests
	cd mcp && uv run ruff check src tests
	cd mcp && uv run mypy src

mcp-test:
	cd mcp && uv run pytest tests

clean: docs-clean
	rm -rf dist build .mypy_cache .ruff_cache .pytest_cache app/.build app/.wheels mcp/.build mcp/.wheels
	find . -type d -name __pycache__ -prune -exec rm -rf {} +
