import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// One auto-generated sidebar spanning the hand-written guides and the generated ``api``
// subdirectory. Page order comes from each page's ``sidebar_position`` frontmatter.
const sidebars: SidebarsConfig = {
  docs: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
